services:
  db:
    image: postgres:15-alpine
    container_name: church_erp_db
    restart: always
    environment:
      POSTGRES_USER: church_admin
      POSTGRES_PASSWORD: church_password
      POSTGRES_DB: church_db
    ports:
      - "5432:5432"
    volumes:
      - church_erp_data:/var/lib/postgresql/data

  server:
    build: 
      context: ./server
      args:
        DATABASE_URL: postgresql://church_admin:church_password@db:5432/church_db?schema=public
    container_name: church_erp_server
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://church_admin:church_password@db:5432/church_db?schema=public
      JWT_SECRET: super-secret-key-change-this-in-production
      ALLOWED_ORIGINS: https://app.truechurch.com.br,http://app.truechurch.com.br,http://localhost:3000
    ports:
      - "3001:3000"

  client:
    build: 
      context: ./client
      args:
        NEXT_PUBLIC_API_URL: https://api.truechurch.com.br
    container_name: church_erp_client
    restart: always
    depends_on:
      - server
    environment:
      NEXT_PUBLIC_API_URL: https://api.truechurch.com.br
    ports:
      - "3005:3000"

volumes:
  church_erp_data:
